GreenWiNit/GreenWiNit-FE

package.json

add lint process

---

CONTRIBUTING.md
README.md
package.json

Document the project

---

src/api/users.ts
src/components/common/user-card.tsx
src/components/edit-profile-screen/nickname-checkt-input/current-nickname.tsx
src/components/my-page-screen/points-history-filter/index.tsx
src/hooks/use-user-id.ts
src/hooks/use-user-me.ts
src/hooks/use-user-name.ts
src/hooks/use-user-point-history.ts
src/hooks/use-user-points.ts
src/hooks/use-user-status.ts

- ex) 마이페이지 > 포인트 필터 기능 퍼블리싱 완료

[Feat] #112 Add current user api

---

package-lock.json
package.json
src/api/address.ts
src/components/common/form/error-message.tsx
src/components/common/form/input.tsx
src/components/common/page-container.tsx
src/hooks/use-adress.ts
src/main.tsx
src/pages/point-shop/products/[pointProductId]/enroll-address.tsx

- `@hookform/error-message`를 설치했습니다.
- src/components/common/form/error-message.tsx 컴포넌트를 추가 했습니다.
- updateAddress, saveAddress 내부 로직에서 throwResponseStatusThenChaining을 사용하도록 변경했습니다.
- input 컴포넌트의 selectcion이 잘 보이지 않아서 색을 변경했습니다. (기존 primary 색)
- PageContainer의 maxHeight를 설정했습니다.
- useAddress에서 retry를 설정했습니다. (off)
- fetch response interceptor 설정할 때 clone하여 사용하도록 수정했습니다.
- 디자인 시안에 가깝게 수정했습니다. (하단 사진 참고)

[Fix] #122 delivery address api handling issue

---

src/App.tsx
src/components/common/user-card.tsx
src/hooks/use-user-status.ts
src/pages/point-shop/products/[pointProductId]/detail.tsx

[Refactor] Not call api if logged in

---

src/App.css
src/App.tsx
src/index.css

[Fix] mobile layout below 375px

---

src/api/challenges.ts
src/routes/challenges/$challenge-id/detail.tsx

[Feat] #191 TS054

---

src/routes/challenges/$challenge-id/detail.tsx

[Feat]: #194 TS053

---

src/components/common/user-card.tsx

[Feat]: #200 TS066 

---

src/routes/challenges/$challenge-id/teams/enroll.tsx

[Feat] #179 TS060

---

src/api/challenges.ts
src/components/common/teams/team-card.tsx

[Feat] #217 TS062

---

src/api/challenges.ts
src/components/common/teams/overview.tsx

[Feat] #164 TS073

---

src/components/my-page-screen/certified-challenges-container.tsx

[Feat] #220 TS075

---

src/routes/point-shop/products/$point-product-id/detail.tsx

TS 086 에서 포인트 교환 성공 후 확인 메시지의 문구 변경 요청을 받아 작업하였습니다.
https://www.notion.so/254adf41302d80f08203c7e1b013a072

[Fix] exchange point notifiy dialog modify

---

src/routes/challenges/$challenge-id/teams/$team-id/joined.tsx

[Feat] #233 TS091

---

src/components/common/teams/team-card.tsx
src/constant/globals.ts

[Feat] #246 TS103

---

src/api/users.ts
src/components/edit-profile-screen/nickname-checkt-input/input-nickname.tsx

HotFix: wrong typing

---

src/components/edit-profile-screen/nickname-checkt-input/input-nickname.tsx

feat: call setHasTriedDuplicateCheck

---

src/routes/signup.tsx

fix: toggle logic to opposite

---

src/api/users.ts
src/routes/login.tsx
src/routes/signup.tsx

[Feat] #254 Update token on signup

---

src/components/shop-screen/user-statusbar.tsx

포인트 상점 포인트 위치 부분 수정입니다.
피드백 나왔던 포인트 위치 변경 부분 건 수정완료하였습니다

[Fix] change-location-point-history

---

src/routes/signup.tsx

조건부에서 잘못 참조되어 throw new Error가 되고 있었던 부분 bugfix 작업입니다.

fix: line71 in signup.tsx

---

src/api/auth.ts
src/components/common/teams/overview.tsx
src/components/common/teams/team-card.tsx
src/constant/globals.ts
src/main.tsx
src/routes/__root.tsx
src/routes/index.tsx
src/routes/my-page/index.tsx
src/routes/signup.tsx

https://github.com/GreenWiNit/backend/issues/329

[Feat] #263 Apply auth api v2

---

index.html
public/naver9451e6d41b4611adf2f05693e1274e73.html

네이버 사이트 소유확인에서 HTML 파일 다운로드 방법을 권장한다고 해 기존에 meta 태그는 삭제하고, html 파일로 추가한 작업입니다.

feat: download navert vertification html in public

---

index.html

index.html에 og:url, og:image가 잘못되어 있어 수정한 작업입니다.

chore: change og url and og image link

---

src/components/post-screen/category-name.tsx
src/components/post-screen/post-item.tsx

포스트 카드의 크기 이미지와 텍스트 크기 안 맞는 이슈 수정
- use line-clamp
- remove substring

fix: post styling fixed
